name: Deploy to Github Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_CACHEDIR: /tmp/hugo_cache
    permissions:
      contents: write
    steps:

      # Clones the repository. We also want the submodules, thats where the theme lies.
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          
      # Enable caching for Hugo modules
      - uses: actions/cache@v4
        with:
          path: ${{ env.HUGO_CACHEDIR }} 
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      # Download, and sets up HUGO, ready for use in GHActions
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: "latest"
          extended: true

      # Builds the ./public, and minifies CSS/JS
      - name: Build
        run: hugo --minify

      # Takes the result of ./public, and pushes it to the `gh-pages` branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
